using RiotProxy.Domain;
using MySqlConnector;

namespace RiotProxy.Infrastructure.Persistence
{
    public class UserRepository
    {
        private readonly IDbConnectionFactory _factory;

    public UserRepository(IDbConnectionFactory factory)
    {
        _factory = factory;
    }

        public async Task<User?> GetByUserNameAsync(string userName)
        {
            await using var conn = _factory.CreateConnection();

            await conn.OpenAsync();

            const string sql = "SELECT UserId, UserName FROM User WHERE UserName = @userName";
            await using var cmd = new MySqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("@userName", userName);

            await using var reader = await cmd.ExecuteReaderAsync();
            if (!await reader.ReadAsync()) return null;

            return new User
            {
                UserId = reader.GetInt32(0),
                UserName = reader.GetString(1)
            };
        }
        
        public async Task<User?> CreateUserAsync(string userName)
        {
            Console.WriteLine("Creating user in database...");
            await using var conn = _factory.CreateConnection();
            await conn.OpenAsync();

            //    We only insert the UserName; UserId is generated by the DB.
            const string sql = @"
                INSERT INTO User (UserName)          
                VALUES (@userName);
                SELECT LAST_INSERT_ID();             
            ";
            Console.WriteLine("SQL prepared.");
            await using var cmd = new MySqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("@userName", userName);
            Console.WriteLine("Parameters added.");
            //    ExecuteScalarAsync returns the first column of the first row,
            //    which is the value produced by LAST_INSERT_ID().
            var result = await cmd.ExecuteScalarAsync();
            Console.WriteLine("Command executed.");
            // If the insert failed for any reason, result could be null.
            if (result == null || result == DBNull.Value)
                return null;
            Console.WriteLine("User created");
            // 4️⃣ Build and return the User object.
            var newUser = new User
            {
                UserId   = Convert.ToInt32(result), // the auto‑generated id
                UserName = userName
            };

            return newUser;
        }
    }
}