name: Client - Vue.js CI

on:
  push:
    branches: [main]                     # ← only pushes to the *main* branch
    paths:
      - 'client/**'                      # ← run only when something under client/ changees
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client   # All commands run inside client/
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest with coverage
        run: npm run test:unit:coverage

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./client/dist/
          server-dir: ${{ secrets.FTP_CLIENT_PATH }}
