name: CI - Server

# -------------------------------------------------
# When the workflow runs
# -------------------------------------------------
on:
  push:
    branches: [main]
    paths:
      - 'server/**'          # Only run when something under server/ changes
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
  workflow_dispatch:         # Manual trigger

# -------------------------------------------------
# Jobs definition
# -------------------------------------------------
jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    # Run everything from the server directory (optional)
    defaults:
      run:
        working-directory: ./server

    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'   # ← change if you need a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install your project deps first
          pip install -r requirements.txt
          # Install tools we'll use for CI
          pip install pytest ruff mypy

   
      - name: Run ruff linting
        run: |
          # format=github makes the output appear as annotations in the PR UI
          ruff check . --format=github

      - name: Run mypy type checking
        run: |
          # show-error-codes gives clearer messages
          mypy . --show-error-codes

    
      - name: Run pytest
        run: |
          pytest -v                     # add flags like --cov or --junitxml if desired