name: CI - Client

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'client/**'            # Only run when something under client/ changes
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'client/**'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client   # All commands run inside client/
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest with coverage
        run: npm run test:unit:coverage
